### ISSUE TITLE
异步调用的问题

### ISSUE THREAD

**Issue by awxtggg** [humornif/Demo-Code#1]
十分感谢王老师，程序已经可以正常运行了，但在编译时，编译器提醒以下二个地方未使用异步方法，这个警告可以直接忽略吗？对于系统性能及服务器内存的使用是否会有什么影响？谢谢。
https://github.com/humornif/Demo-Code/blob/9c1956c2279746a051bdb12467bbc1e5d9822fd2/DemoChannel/DemoChannel/Program.cs#L15

提示信息：“警告	CS1998	此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上执行占用大量 CPU 的工作。”
同时提示DataHandle.cs文件的Handleer函数：警告CS1998	此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上执行占用大量 CPU 的工作。

**Comment by humornif** [comment]
哦，刚看到。这个没问题。在异步方法里，如果一个异步或多线程调用，没有await，就会有这个警告。
